### ISSUE TITLE
Support for multiple capabilities

### ISSUE THREAD

**Issue by devantler** [fopina/docker-portainer-capability-manager#1]
I am trying to add multiple capabilities to a service, but as the labels have the same name it is not allowed.

```
    deploy:
      labels:
        io.portainerhack.cap_add: NET_ADMIN
        io.portainerhack.cap_add: SYS_MODULE
      mode: replicated
      replicas: 1
```

Is there a way to do this, I could not find anything in the README :-)

**Comment by fopina** [comment]
it's comma-separated ([code](https://github.com/fopina/docker-portainer-capability-manager/blob/main/portainerhack/__main__.py#L27-L28))

```yaml
    deploy:
      labels:
        io.portainerhack.cap_add: NET_ADMIN,SYS_MODULE
      mode: replicated
      replicas: 1
```
